version: '3'

services:
  db:
    image: hypriot/rpi-mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - MYSQL_ROOT_PASSWORD=test123
    env_file:
      - db.env

  app:
    image: nextcloud:fpm
    restart: always
    volumes:
      - nextcloud:/var/www/html
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db

  web:
    image: secure_web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - VIRTUAL_HOST=itprojekt-nextcloud.duckdns.org
      - LETSENCRYPT_HOST=itprojekt-nextcloud.duckdns.org
      - LETSENCRYPT_EMAIL=hendrik.boerste@gmail.com
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  proxy:
    image: secure_proxy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 5000:50000
      - 5222:5222
      - 5269:5269
      - 5280:5280
      - 5281:5281
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: rpi-docker-letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - ACME_TOS_HASH=cc88d8d9517f490191401e7b54e9ffd12a2b9082ec7a1d4cec6101f9f1647e7b
    networks:
      - proxy-tier
    depends_on:
      - proxy

  portainer:
      image: portainer/portainer
      restart: always
      volumes:
        - portainer_data:/data
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 9000:9000
      deploy:
        replicas: 1
        placement:
          constraints: [node.role == manager]

  prosody:
    image: rpi-prosody
    restart: always
    ports:
      - 5000:50000
      - 5222:5222
      - 5269:5269
      - 5280:5280
      - 5281:5281
    volumes:
      - /etc/nginx/certs/itprojekt-nextcloud.duckdns.org/key.pem:/usr/local/etc/prosody/certs/prosody.key
      - /etc/nginx/certs/itprojekt-nextcloud.duckdns.org/fullchain.pem:/usr/local/etc/prosody/certs/prosody.crt
      - ./prosody:/usr/local/var/lib/prosody
    environment:
      - DOMAIN=itprojekt-nextcloud.duckdns.org
      - VIRTUAL_HOST=itprojekt-nextcloud.duckdns.org
      - LETSENCRYPT_HOST=itprojekt-nextcloud.duckdns.org
      - LETSENCRYPT_EMAIL=hendrik.boerste@gmail.com
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]


volumes:
  db:
  nextcloud:
  certs:
  conf.d:
  vhost.d:
  html:
  portainer_data:

networks:
  proxy-tier:
