version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
    env_file:
      - db.env

  app:
    image: nextcloud:fpm
    restart: always
    volumes:
      - nextcloud:/var/www/html
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - POSTGRES_HOST=db
    env_file:
      - db.env
    depends_on:
      - db

  web:
    image: hendrikboerste/nginx-web
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html:ro
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  portainer:
      image: portainer/portainer
      restart: always
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 9000:9000
      deploy:
        replicas: 1
        placement:
          constraints: [node.role == manager]

  backup:
    image: hendrikboerste/cron-backup
    volumes:
      - nextcloud:/volume
      - /home/pi/backup:/backup
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    depends_on:
      - app


volumes:
  db:
  nextcloud:

networks:
  proxy-tier:
